#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# disable capslock, us altgr-intl layout
setxkbmap -option caps:none
setxkbmap -model pc105 -layout us -variant altgr-intl

# rebind capslock to ESC
if [ -s ~/.Xmodmap ]; then
    xmodmap ~/.Xmodmap
fi

# draw desktop background
if [ -s ~/.fehbg ]; then
    sh ~/.fehbg
fi

exec i3
